[droidmedia] FakeSensor support for Android 10. Contributes to JB#54861
sailfishos/droidmedia pull request #80
Opened 2021-07-01 14:38 UTC by MrBam

Adding support of FakeSensor by resolving conflicts of headers

2021-07-01 18:00 UTC, mlehtima requested changes
Tested on Xperia 10 II and works correctly. Some small style complaints, otherwise looks ok.

2021-07-02 10:04 UTC, MrBam commented on services/services_10_0_0.h
>  using namespace android;
yes, because of using namespace android; were all the issue of aLooper ambiguous.

2021-07-02 13:33 UTC, mlehtima approved these changes

2021-07-02 13:34 UTC, abranson approved these changes

2021-07-02 14:45 UTC, merged